name: pkg-test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pkg-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setup R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
          use-public-rspm: true

      # 3. Install system libraries needed by sf/terra/s2/etc.
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev \
            cmake \
            libabsl-dev \
            texlive-base \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-science \
            lmodern \
            pandoc

      # 4. Install pak and use it to install your R package's dependencies
      - name: Install pak and package dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev")
          pak::install_deps(dependencies = TRUE)

      # 5. Run R CMD check
      - name: Run R CMD check
        run: R CMD check --no-manual --as-cran .
